// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtU1pjyNUC8Svf-7310FHuJs76kCdBUY',
    appId: '1:599144522989:web:8abe33d6fdd86a5d2718e4',
    messagingSenderId: '599144522989',
    projectId: 'flutter-demo-f70c5',
    authDomain: 'flutter-demo-f70c5.firebaseapp.com',
    storageBucket: 'flutter-demo-f70c5.appspot.com',
    measurementId: 'G-QZ16KMEDSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHzdM2Qf6TVX2vDNxds_l6mFzokqCJLBg',
    appId: '1:599144522989:android:4bff7e1a5b06955d2718e4',
    messagingSenderId: '599144522989',
    projectId: 'flutter-demo-f70c5',
    storageBucket: 'flutter-demo-f70c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgPIAM1a2rVYF6dqAR3JI7-FsdAF_GtuU',
    appId: '1:599144522989:ios:480a2e54bff86d492718e4',
    messagingSenderId: '599144522989',
    projectId: 'flutter-demo-f70c5',
    storageBucket: 'flutter-demo-f70c5.appspot.com',
    iosClientId: '599144522989-3jk14fdf095egrbc6i8isu6nlprd6cnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeshareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgPIAM1a2rVYF6dqAR3JI7-FsdAF_GtuU',
    appId: '1:599144522989:ios:480a2e54bff86d492718e4',
    messagingSenderId: '599144522989',
    projectId: 'flutter-demo-f70c5',
    storageBucket: 'flutter-demo-f70c5.appspot.com',
    iosClientId: '599144522989-3jk14fdf095egrbc6i8isu6nlprd6cnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeshareapp',
  );
}
